app/models/ad.py
#importando a classe db do objeto app
from app import db

#criando a classe que representa a tabela campaign_set
class Ad(db.Model):
    #atributo que se refere ao nome real da tabela no bando de dados
    __tablename__ = "ad"

    #atributos que se referem ao campos da tabela
    ad_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    ad_set_id = db.Column(db.Integer, db.ForeignKey('ad_set.ad_set_id'))
    campaign_creative = db.Column(db.String)
    cta_link = db.Column(db.String)
    agency_id = db.Column(db.Integer, db.ForeignKey('agency.agency_id'))


    #buscando as relações de chave estrangeiras nas tabelas equivalentes
    ad_set = db.relationship('Ad_Set', back_populates='ad', foreign_keys='Ad.ad_set_id')
    
    agency = db.relationship('Agency', back_populates='ad', foreign_keys='Ad.agency_id')

    file = db.relationship('File', back_populates='ad', primaryjoin='Ad.ad_id==File.ad_id', cascade='all, delete-orphan')

    #método construtor
    def __init__(self, name, ad_set_id, campaign_creative, cta_link, agency_id):
        self.name = name
        self.ad_set_id = ad_set_id
        self.campaign_creative = campaign_creative
        self.cta_link = cta_link
        self.agency_id = agency_id

    #método de representação
    def __repr__(self):
        return "<Ad %r>" % self.name

    

app/models/adset.py
#importando a classe db do objeto app
from app import db

from datetime import datetime

#criando a classe que representa a tabela campaign_set
class Ad_Set(db.Model):
    #atributo que se refere ao nome real da tabela no bando de dados
    __tablename__ = "ad_set"

    #atributos que se referem ao campos da tabela
    ad_set_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    campaign_id = db.Column(db.Integer, db.ForeignKey('campaign.campaign_id'))
    date_start = db.Column(db.DateTime)
    date_end = db.Column(db.DateTime)
    public = db.Column(db.String)
    budget = db.Column(db.Integer)
    total_budget = db.Column(db.Numeric, db.Computed('budget * (date_end - date_start.day)'))
    agency_id = db.Column(db.Integer, db.ForeignKey('agency.agency_id'))
    

    #buscando as relações de chave estrangeiras nas tabelas equivalentes
    campaign = db.relationship('Campaign', back_populates='ad_set', foreign_keys='Ad_Set.campaign_id')
    
    agency = db.relationship('Agency', back_populates='ad_set', foreign_keys='Ad_Set.agency_id')

    ad = db.relationship('Ad', back_populates='ad_set', primaryjoin='Ad_Set.ad_set_id==Ad.ad_set_id', cascade='all, delete-orphan')

    #método construtor
    def __init__(self, name, campaign_id, date_start, date_end, public, budget, agency_id):
        self.name = name
        self.campaign_id = campaign_id
        self.date_start = date_start
        self.date_end = date_end
        self.public = public
        self.budget = budget        
        self.agency_id = agency_id

    #método de representação
    def __repr__(self):
        return "<Add_Set %r>" % self.name

    

app/models/campaign.py
#importando a classe db do objeto app
from app import db

from datetime import datetime

#criando a classe que representa a tabela campaign_set
class Campaign(db.Model):
    #atributo que se refere ao nome real da tabela no bando de dados
    __tablename__ = "campaign"

    #atributos que se referem ao campos da tabela
    campaign_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    campaign_set_id = db.Column(db.Integer, db.ForeignKey('campaign_set.campaign_set_id'))
    date_creation = db.Column(db.DateTime)
    campaign_objective_id = db.Column(db.Integer, db.ForeignKey('campaign_objective.campaign_objective_id'))
    agency_id = db.Column(db.Integer, db.ForeignKey('agency.agency_id'))

    #buscando as relações de chave estrangeiras nas tabelas equivalentes
    campaign_set = db.relationship('Campaign_Set', back_populates='campaign', foreign_keys='Campaign.campaign_set_id')

    ad_set = db.relationship('Ad_Set', back_populates='campaign', primaryjoin='Campaign.campaign_id==Ad_Set.campaign_id', cascade='all, delete-orphan')
    
    campaign_objective = db.relationship('Campaign_Objective', foreign_keys=campaign_objective_id)

    agency = db.relationship('Agency', back_populates='campaign', foreign_keys='Campaign.agency_id')


    #método construtor
    def __init__(self, name, campaign_set_id, campaign_objective_id, agency_id):
        self.name = name
        self.campaign_set_id = campaign_set_id
        self.campaign_objective_id = campaign_objective_id
        self.date_creation = datetime.now()
        self.agency_id = agency_id

    #método de representação
    def __repr__(self):
        return "<Campaign %r>" % self.name

    

app/models/campaignset.py
#importando a classe db do objeto app
from app import db

from datetime import datetime

#criando a classe que representa a tabela campaign_set
class Campaign_Set(db.Model):
    #atributo que se refere ao nome real da tabela no bando de dados
    __tablename__ = "campaign_set"

    #atributos que se referem ao campos da tabela
    campaign_set_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    date_creation = db.Column(db.DateTime)
    agency_id = db.Column(db.Integer, db.ForeignKey('agency.agency_id'))

    campaign = db.relationship('Campaign', back_populates='campaign_set', primaryjoin='Campaign_Set.campaign_set_id==Campaign.campaign_set_id', cascade='all, delete-orphan')

    agency = db.relationship('Agency', back_populates='campaign_set', foreign_keys='Campaign_Set.agency_id')

    #método construtor
    def __init__(self, name, agency_id):
        self.name = name
        self.date_creation = datetime.now()
        self.agency_id = agency_id

    def __repr__(self):
        return "<Campaign_Set %r>" % self.name

    

app/controllers/simplepage.py
from flask import Blueprint, redirect, url_for, render_template, request, flash, session, jsonify
from flask_login import login_user, logout_user
from app.models.user import *
from app.models.login import LoginForm
from app.models.formuser import UserForm
from app.models.agency import *
from app.models.formagency import *
from app.models.credential import Credential
from app.models.campaignset import Campaign_Set
from app.models.campaign import Campaign
from app.models.adset import Ad_Set
from app import db

simplepage = Blueprint('simplepage', __name__, static_folder="static", template_folder="templates")



@simplepage.route('/register/', methods=["GET", "POST"])
def register():

    form = UserForm()
    form.agency.choices = [(g.agency_id, g.name) for g in Agency.query.all()]
      
    if form.validate_on_submit():
        objective = form.agency.data
        name = form.username.data
        password = form.password.data
        rpassword = form.rpassword.data
        agency_set_id = Agency.query.filter_by(agency_id=objective).first()
        newuser = User.query.filter_by(agency_id=agency_set_id.agency_id).first()

        if not newuser:
            credential = Credential("Responsavel", 1)
            print(credential)
            db.session.add(credential)
            db.session.commit()

        else:
             credential = Credential("convidado", 0)
             db.session.add(credential)
             db.session.commit()
             print(credential)

        if password != rpassword:
            flash('Digite a mesma senha') 
            return redirect(url_for('simplepage.register'))

        #credential_id = Credential.query.filter_by(credential_id=credential).first()
        reg = User(name, agency_set_id.agency_id, password, credential.credential_id)
        db.session.add(reg)
        db.session.commit()
            
        
        return redirect(url_for('simplepage.login'))

    return render_template('register.html', form=form)


@simplepage.route('/addagency', methods=["GET", "POST"])
def addagency():

    form = AgencyForm()

    if form.validate_on_submit():
        objective1 = form.newagency.data
        addagency = Agency(objective1)
        db.session.add(addagency)
        db.session.commit()
        return redirect(url_for('simplepage.register'))
    
    return render_template('newagency.html', form=form)


@simplepage.route('/login', methods=["GET", "POST"])
def login():
    if "user" in session:
        return redirect(url_for('index'))    
    
    else:
        form = LoginForm()

        if form.validate_on_submit():
            name = form.username.data
            pwd = form.password.data
            #user = User.query.get(form.name.data)
            user = User.query.filter_by(name=name).first()
            #agencyid = User.query.filter_by(agency_id=agency_id).first
        

            if not user or not user.verify_password(pwd):
                flash("invalid login")
                return render_template('loginpage.html', form=form)

            login_user(user)
            session["user"] = name, user.agency_id, user.credential_id
            return redirect(url_for('index'))
    
        return render_template('loginpage.html', form=form)


@simplepage.route('/useragency', methods=["GET", "POST"])
def useragency():

    if "user" in session:
        form = AgencyFormChoices()
        form.user_id.choices = [(g.credential_id, g.name) for g in User.query.filter_by(agency_id=session["user"][1]).all()]

        user_choice = form.user_id.data
        permissao = form.permissao.data
        if user_choice and permissao == "permitir":
            credential = Credential.query.filter_by(credential_id=user_choice).first()
            if credential.name  == "Responsavel":
                flash('Não tem permissão para essa ação')
                return redirect(url_for('index'))    
            credential.name = "User"
            db.session.commit()
            credential.habilitie_01 = True
        
            db.session.commit()
            return redirect(url_for("index"))
        
        if user_choice and permissao == "negar":
            credential = Credential.query.filter_by(credential_id=user_choice).first()
            if credential.name  == "Responsavel":
                flash('Não tem permissão para essa ação')
                return redirect(url_for('index'))
            credential.name = "Convidado"
            db.session.commit()
            credential.habilitie_01 = False
            db.session.commit()
            return redirect(url_for("index"))

        return render_template('useragency.html', form=form)
    else:
        return redirect(url_for("simplepage.login"))


@simplepage.route('/logout')
def logout():
    session.pop("user", None)
    logout_user()
    return redirect(url_for('simplepage.login'))


@simplepage.route('/apiexterna')
def apiexterna():
    agency_check = session['user'][1]
    print(agency_check)
    camp_set_info = Campaign_Set.query.filter_by(agency_id=agency_check).all()
    camp_info = Campaign.query.filter_by(agency_id=agency_check).all()
    ad_info = Ad_Set.query.filter_by(agency_id=agency_check).all()
    
    x = 0
    camp_set_name = []
    camp_name = []
    adname_j = []
    adpublic = []
    adbudget = []
    date_start = []
    date_end = []
    apiex = {}
    total = 0
    
    while(True): #Criação do objeto Json. 
        camp_name.append(camp_info[x].name)
        camp_set_name.append(camp_set_info[x].name)
        adname_j.append(ad_info[x].name)
        date_start.append(ad_info[x].date_start)
        date_end.append(ad_info[x].date_end)
        adpublic.append(ad_info[x].public)
        adbudget.append(ad_info[x].total_budget)
        total = total + adbudget[x]
        x = x + 1
        if x == len(camp_set_info):
            apiex['1 - Campanha'] = camp_name
            apiex['2 - Campanha Name'] = camp_set_name
            apiex['3 - Ad name'] = adname_j
            apiex['4 - Publico Alvo'] = adpublic
            apiex['5 - Data de Inicio'] = date_start
            apiex['6 - Data de Termino'] = date_end
            apiex['7 - Budget por campanha'] = adbudget
            apiex['8 - Total'] = total
            break

    '''api = camp_set_info[0].name'''
    return jsonify(apiex) #Transformando o dicionario em Json.

app/templates/about.html
{% extends "base.html" %}

{% block content %}
    <head> 
        <title>Sobre</title>
        <link rel ="stylesheet" href = "{{ url_for('static', filename = "css/bootstrap.min.css") }}">
    </head>

<body>
<h1>Sobre</h1>

<h3>
    Protótipo de plataforma web que distribui o orçamento durante o período de uma campanha de marketing digital. Requisito da disciplina "Projeto Integrador em Computação II", 5º semestre dos cursos de Ciência de Dados e Engenharia da Computação, da Univesp.<br><br> 
    Fazem parte deste projeto os alunos:<br>
     Alessandra Dan<br>
     Fernando Palhares <br>
     Itamar de Oliveira <br>
     Joice Oliveira <br>
     Marcos Antonio do Nascimento<br>
     Weslley da Silva <br>
     Orientadora: Cláudia Silva
</h3>    


<script src=" {{url_for('static', filename = "js/bootstrap.min.js") }}"></script>
</body>
{% endblock %}

app/templates/ad.html
{% extends "base.html"}

{% block content %}
    <h1>Anúncio</h1>
{% endblock %}

app/templates/adcreate.html
{% extends "base.html" %}

{% block content %}
    <div class="inline">
        <h3><a href="{{ url_for('index') }}" >Início</a> >
            <a href="{{ url_for('campaignset', campaignset_id=campaign.campaign_set_id)}}">{{ campset.name }}</a> >
            <a href="{{ url_for('campaign', campaign_id=campaign.campaign_id)}}">{{ campaign.name }}</a> >
            <a href="{{ url_for('adset', adset_id=adset.ad_set_id)}}">{{ adset.name }}</a> > 
            Novo Anúncio
        </h3>
    </div>
    <form action="" method="POST">
        {{ form.csrf_token }}
        <h2>Nome do Anúncios</h2>
        <div class="form-group"> 
            <label>Nome</label>
            {{ form.name(class="form-control", placeholder="Escreva um nome") }}
            <label>Criativo</label>
            {{ form.campaign_creative(class="form-control", placeholder="Descreva") }}
            <label>Link</label>
            {{ form.cta_link(class="form-control", placeholder="Saída do Anúncio") }}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        {% if form.errors.name %}
            <div class="alert alert-danger" role="alert">
                {{ forms.errors.name }}
            </div>
        {% endif %}
    </form>
{% endblock %}

app/templates/adsetcreate.html
{% extends "base.html" %}

{% block content %}
    <div class="inline">
        <h3><a href="{{ url_for('index') }}" >Início</a> >
            <a href="{{ url_for('campaignset', campaignset_id=campaign.campaign_set_id)}}">{{ campset.name }}</a> >
            <a href="{{ url_for('campaign', campaign_id=campaign.campaign_id)}}">{{ campaign.name }}</a> > 
            Novo Conjunto de Anúncios
        </h3>
    </div>
    <form action="" method="POST">
        {{ form.csrf_token }}
        <h2>Nome do Conjunto de Anúncios</h2>
        <div class="form-group"> 
            <label>Nome</label>
            {{ form.name(class="form-control", placeholder="Escreva um nome") }}
            <label>Data de Início</label>
            {{ form.date_start(class="form-control", placeholder="dd/mm/aaaa") }}
            <label>Data de Término</label>
            {{ form.date_end(class="form-control", placeholder="dd/mm/aaaa") }}
            <label>Descrição de Público</label>
            {{ form.public(class="form-control", placeholder="Descreva o Público Alvo") }}
            <label>Orçamento</label>
            {{ form.budget(class="form-control", placeholder="R$ por dia") }}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        {% if form.errors.name %}
            <div class="alert alert-danger" role="alert">
                {{ forms.errors.name }}
            </div>
        {% endif %}
    </form>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}"/>
    <link rel='stylesheet' href="{{url_for('static', filename='font-awesome/css/all.css')}}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Calculadora de Campanha</title>
  </head>
  <body>
     <!-- Acessibilidade - Botão para pular conteúdo 
    Lógica do procedimento: referencia o conteudo principal na href. 
    Como o site não utilizou html semântico, precisa usar o tabindex="0" em todas as divs e elementos
    -->
    <a class="pular-conteudo" href="#container" tabindex="1">Pular para conteúdo</a>
    {% include "navbar.html" %}
    <div id="container" class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <!-- Acessibilidade: funcionalidades para botões de aumento e redução de fonte -->
    
    <script type="text/javascript">
      window.onload = function() {
          var elementBody = document.querySelector('body');
          var elementBtnIncreaseFont = document.getElementById('increase-font');
          var elementBtnDecreaseFont = document.getElementById('decrease-font');
          // Padrão de tamanho, equivale a 100% do valor definido no Body
          var fontSize = 100;
          // Valor de incremento ou decremento, equivale a 10% do valor do Body
          var increaseDecrease = 10;

          // Evento de click para aumentar a fonte
          elementBtnIncreaseFont.addEventListener('click', function(event) {
              fontSize = fontSize + increaseDecrease;
              elementBody.style.fontSize = fontSize + '%';
          });

          // Evento de click para diminuir a fonte
          elementBtnDecreaseFont.addEventListener('click', function(event) {
              fontSize = fontSize - increaseDecrease;
              elementBody.style.fontSize = fontSize + '%';
          });
      }
    </script>

    <!-- JS para o botão de alto e baixo contraste-->
    <script type="text/javascript">
        const check = document.getElementById('check')
  
        check.addEventListener('change', () => {
          document.body.classList.toggle('dark')
        })

        check.addEventListener("keypress", () => {
          document.body.classList.toggle('dark')
        })
        

    </script>
  

     <!-- Inserção de VLibras. O Pluggin é disponibilizado pelo governo federal -->
     <div vw class="enabled">
      <div vw-access-button class="active"></div>
      <div vw-plugin-wrapper>
        <div class="vw-plugin-top-wrapper"></div>
      </div>
    </div>
    <script src="https://vlibras.gov.br/app/vlibras-plugin.js"></script>
    <script>
      new window.VLibras.Widget('https://vlibras.gov.br/app');
    </script>

  </body>
</html>

app/templates/campaign.html
{% extends "base.html" %}

{% block content %}
    <div class="inline"> 
        <h3><a href="/" >Início</a> > 
            <a href="{{ url_for('campaignset', campaignset_id=campset.campaign_set_id) }}"> {{ campset.name }} </a> > 
            {{ campaign.name }}
        </h3>
    </div>
    <ul>
        <li>Campanha: {{ campaign.name }}</li>
        <li>Objetivo: {{ campaign.campaign_objective.name }}</li>
        <li>Data de Criação: {{ campaign.date_creation }}</li>
    </ul>
    <div class="flex">
        <h2>Conjuntos de Anúncios</h2>
    </div>
    <div>
        <ul class="content-list">
            <li class="content-add card list-card" onclick="newadset()" tabindex="0"><h5>Novo</h5><i class="fas fa-plus"></i></li>
            {% for adset in adset %}
                <li class="card list-card" onClick="getadset()" tabindex="0">
                    <div class="content-in-top">
                        <i class="fas fa-trash-alt" onClick="adsetremove()" tabindex="0"></i>
                    </div> 
                    <div>
                        <p class="card-title">ID: {{ adset.ad_set_id }}</p>
                        <h5 class="card-title">{{ adset.name }}</h5>
                        <p class="card-text close-to">Início:</p>
                        <p class="card-text">{{ adset.date_start.strftime('%d-%m-%Y') }}</p>
                        <p class="card-text close-to">Fim:</p>
                        <p class="card-text">{{ adset.date_end.strftime('%d-%m-%Y') }}</p>
                        <p class="card-text">{{ adset.public }}</p>
                        <p class="card-text">R${{ adset.budget }}/dia</p>
                        <p class="card-text">Total: R${{ adset.total_budget }}</p>
                        <p class="card-text close-to">Anúncios:</p>
                        {% for ad in adset.ad %}
                            <p class="card-text close-to">{{ ad.ad_id}} - {{ ad.name }}</p>
                        {% endfor %}
                    </div>
                    <param name="id" value={{ adset.ad_set_id }}>
                </li>
            {% endfor %} 
        </ul>
    </div>


    <script>
        function getadset(){
        //campid = event.target.parentElement.querySelector('param').getAttribute('value');
        //window.location.href = window.location + "campaign/" + campid;
        window.location.href = window.location.origin + "/adset/" + event.target.parentElement.parentElement.querySelector('param').getAttribute('value');
        //alert(window.location + "campaign/" + campid)
    }

        function newadset(){
            window.location.href = window.location.origin + "/adsetcreate/" + window.location.pathname.split('/').pop()
        }

        function adsetremove(){
            adsetId = event.target.parentElement.parentElement.querySelector('* param').getAttribute('value');
            window.location.href = window.location.origin + "/adsetremove/" + adsetId;
            event.stopPropagation();
        }
    </script>

                            <!-- {% if adset.ad %}  
                            {% for ad in adset.ad.ad_id %}
                                <p class="card-text">{{ adset.ad.id }} - {{ adset.ad.name }}</p> 
                            {% endfor %}
                         {% else %}
                        <p class="card-text">Sem Anúncios.</p> 
                        {% endif %}  -->  

{% endblock %}

app/templates/campaigncreate.html
{% extends 'base.html' %}

{% block content %}
    <div class="inline">
        <h3><a href="{{ url_for('index') }}" >Início</a> >
        <a href="{{ url_for('campaignset', campaignset_id=campset.campaign_set_id)}}">{{ campset.name }}</a> > 
        Nova Campanha</h3>
    </div>
    <form action="" method="POST">
        {{ form.csrf_token }}
        <h2>Nova Campanha</h2>
        <div class="form-group">
            <label>Nome</label>
            {{ form.name(class="form-control", placeholder="Escreva um nome") }}
            <label>O Escolha um Objetivo de Campanha</label>
            {{ form.campaignobjective(class="form-select") }}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        {% if form.errors.name %}
            <div class="alert alert-danger" role="alert">
                {{ forms.errors.name }}
            </div>
        {% endif %}
    </form>
{% endblock %}

app/templates/campaignsetcreate.html
{% extends "base.html" %}

{% block content %}
<div>
    <h3><a href="{{ url_for('index') }}" >Início</a> > Novo Conjunto de Campanhas</h3>
</div>
<div id="container" class="container">
    <h2>Dê um nome para o Conjunto de Campanhas</h2>
    <form action="" method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            <label>Nome</label>
            {{ form.name(class="form-control", placeholder="Escreva um nome") }}
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        {% if form.errors.name %}
            <div class="alert alert-danger" role="alert">
                {{ forms.errors.name }}
            </div>
        {% endif %}
    </form>
</div>
{% endblock %}

app/templates/newagency.html
{% extends "base.html" %}

{% block content %}

<form action="" method="POST">
    {{ form.csrf_token }}
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Nova Agencia</label>
        {{ form.newagency(class="form-control", placeholder="name") }}
    </div>

    <div class="col-12">
        <button type="submit" class="btn btn-primary" value="register">Register</button>
    </div>
</form>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row" id="clearLabel">
        <div class="mb-3 w-0 col-sm-4" id="newLabel">
            <a href='{{ url_for("simplepage.addagency") }}' class='btn btn-primary d-grid gap-3 col-6 mx-auto m-3' > Nova Agencia </a>
        </div>

        <div class="col-sm mt-4">
            
        </div>
    </div>
</div>
<form action="" method="POST">
    {{ form.csrf_token }}
    
    <div class="container">
        <div class="row">
            <div class="mb-3 w-0 col-sm-4" id="novalabel">
                <label id="clear">O Nome da Agencia</label>
                    {{ form.agency(class="form-select") }}
            </div>

            <div class="col-sm mt-4" id="novobotao">
               
            </div>
        </div>
    </div>
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">name</label>
        {{ form.username(class="form-control", placeholder="name") }}
    </div>
    <div class="mb-3">
        <label for="formGroupExampleInput2" class="form-label">Password</label>
        {{ form.password(class="form-control", placeholder="password") }}
    </div>
    <div class="mb-3">
        <label for="formGroupExampleInput2" class="form-label">Repeat Password</label>
        {{ form.rpassword(class="form-control", placeholder="password") }}
    </div>
    <div class="col-12">
        <button type="submit" class="btn btn-primary" value="register">Sign in</button>
    </div>
</form>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
            {% for message in messages %}
                    <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}


{% endblock %}

<!--<script>
    let botaoNew = document.querySelector("#new");

    botaoNew.addEventListener('click', function() {
       clearlabel = document.getElementById("clearLabel").remove()
       remove = document.getElementById('clear').remove()
       novaLabel = '<label for="formGroupExampleInput" class="form-label">Nova Agencia</label>{{ form1.newagency(class="form-control") }}';
       novoBotao = "<a href='{{ url_for('simplepage.addagency') }}' class='btn btn-primary d-grid gap-3 col-6 mx-auto m-3' > Adicionar </a>";
       novalabel.innerHTML = novaLabel;
       novobotao.innerHTML = novoBotao;
    });
</script>-->

app/templates/useragency.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {{ form.csrf_token }}
    <div class="subLabel">
    <table class="table table-hover">
        
        <thead class="aju_th">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col" class="permissao">Permissão</th>
                <th scope="col" class="negar">Negar</th>
            </tr>
        </thead>
        <tbody>
        
            <tr>
            
                <th scope="row">1</th>
            
                    <td>  
                        <div class="mb-3 w-0 col-sm-6" id="novoNome">
                            {{ form.user_id(class="form-select") }}
                        </div>
                </td>
                    <td>
                    
                    {% for subfield in form.permissao %}
                        <td>{{ subfield }}</td>
                        
                    {% endfor %}
                    </td>
                
            </tr>
        
        </tbody>
        
    </table>
    </div>
    <div>
        <button type="submit" class="btn btn-success d-grid gap-3 col-6 mx-auto" >Atualizar</button>
    </div>
</form>

{% endblock %}